### ISSUE TITLE
Update support to FreeSurfer 7.X

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/segstats_jsonld#46]
I ran into an error:

% segstats2nidm -add_de -f /Users/kennedyd/Downloads/BL_wks_FS_output/stats/aseg.stats -subjid BLtest -o /Users/davidkennedy/segstats_jsonld/test

Traceback (most recent call last):
  File "/Users/kennedyd/opt/anaconda3/envs/segstats_jsonld/bin/segstats2nidm", line 33, in <module>
    sys.exit(load_entry_point('segstats-jsonld', 'console_scripts', 'segstats2nidm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kennedyd/segstats_jsonld/segstats_jsonld/fs_to_nidm.py", line 764, in main
    [measures, header] = read_stats(stats_file)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kennedyd/segstats_jsonld/segstats_jsonld/fsutils.py", line 198, in read_stats
    raise ValueError(
ValueError: Your file (/Users/kennedyd/Downloads/BL_wks_FS_output/stats/aseg.stats) is adding a new key: FS(structure='Left-Thalamus', hemi='Left', measure='NVoxels', unit='unitless').

DBK suggests: "That’s because FS changed the Left-Thalamus name from Left-Thalamus-Proper to Left-Thalamus in version 7.  The Left-Thalamus CDE isn’t in the FS CDEs because those were done for FS 6.0.  I don’t know how Satra was making those CDEs as he did that work but it needs to be updated FS version 7."

So, how do we update this support???

**Comment by dnkennedy** [comment]
This is a repeat of #44 I guess...

**Comment by dbkeator** [comment]
I did not create the FS CDEs so I do now know now to update these except manually.

**Comment by satra** [comment]
closed via #48
